apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
      - name: ems
        image: employee-management-system:latest
        ports:
        - containerPort: 8080
